version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomoddirectives
    - gosec
    - loggercheck
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
  disable:
    - revive
    - cyclop
    - depguard
    - dogsled
    - dupl
    - dupword
    - err113
    - errchkjson
    - exhaustruct
    - forbidigo
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - grouper
    - importas
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - makezero
    - musttag
    - nestif
    - nlreturn
    - nosprintfhostport
    - testpackage
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
    gocritic:
      disabled-checks:
        - unnamedResult
        - hugeParam
        - rangeValCopy
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      settings:
        rangeValCopy:
          sizeThreshold: 256
    gosec:
      excludes:
        - G115
    govet:
      disable:
        - fieldalignment
    nakedret:
      max-func-lines: 1
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - (.+)_test.go
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - containedctx
        path: pkg/logger/logger.go
        text: "found a struct that contains a context.Context field"
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - (.+)_test.go
      - third_party$
      - builtin$
      - examples$
